import type { Opportunity } from "./types";

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "op-001", sourceEngine: "FREEBIE_FORGE",
    title: "Together.ai — $25 Free API Credits",
    description: "Together.ai is giving new accounts $25 in free inference credits. No card required. Usable on Llama 3, Mixtral, and 30+ open models. Expires 30 days after signup.",
    url: "https://together.ai", tags: ["free","ai","dev","nocredit"], category: "INSTANT_WIN", geoScope: "GLOBAL",
    scoreFriction:1, scorePayout:5, scoreTimeCost:1, scoreCompetition:3, scoreRisk:1, scoreDemand:8, scoreOverall:8.2,
    estimatedValue:"$25", estimatedTime:"3 min",
    steps:["Go to together.ai and click Sign Up","Create account with Google or email","Credits are automatically applied","Use credits to run AI models via API or playground"],
  },
  {
    id: "op-002", sourceEngine: "PAYOUT_PULSE",
    title: "Chase Sapphire — $200 Cashback Signup Bonus",
    description: "Chase Sapphire Preferred is offering a $200 statement credit after spending $500 in the first 3 months. Annual fee waived first year.",
    url: "https://chase.com", tags: ["cashback","creditcard","US"], category: "INSTANT_WIN", geoScope: "US",
    scoreFriction:3, scorePayout:8, scoreTimeCost:2, scoreCompetition:5, scoreRisk:3, scoreDemand:9, scoreOverall:8.5,
    estimatedValue:"$200", estimatedTime:"10 min",
    steps:["Apply online at chase.com/sapphire","Get approved (instant for most)","Spend $500 on anything in 3 months","$200 credit auto-applied to statement"],
  },
  {
    id: "op-003", sourceEngine: "FREEBIE_FORGE",
    title: "Vercel — Free Pro Plan via GitHub Student Pack",
    description: "GitHub Student Dev Pack includes Vercel Pro free for 1 year ($240 value). Any .edu email qualifies.",
    url: "https://education.github.com", tags: ["free","hosting","dev","student"], category: "INSTANT_WIN", geoScope: "GLOBAL",
    scoreFriction:2, scorePayout:7, scoreTimeCost:2, scoreCompetition:2, scoreRisk:1, scoreDemand:7, scoreOverall:8.6,
    estimatedValue:"$240", estimatedTime:"5 min",
    steps:["Go to education.github.com","Verify with .edu email","Activate Vercel Pro from the pack dashboard"],
  },
  {
    id: "op-004", sourceEngine: "MICRO_TASK_MINER",
    title: "UserTesting.com — $10/test (avg 20 min)",
    description: "UserTesting pays $10 per usability test, avg 20 minutes. Tests available daily. No skills required.",
    url: "https://usertesting.com", tags: ["microtask","noskills","global","paypal"], category: "INSTANT_WIN", geoScope: "GLOBAL",
    scoreFriction:2, scorePayout:6, scoreTimeCost:2, scoreCompetition:4, scoreRisk:1, scoreDemand:8, scoreOverall:8.1,
    estimatedValue:"$10–30/hr", estimatedTime:"20 min/test",
    steps:["Sign up at usertesting.com","Complete a short sample test to qualify","Tests appear in dashboard","Get paid via PayPal within 7 days"],
  },
  {
    id: "op-005", sourceEngine: "AFFILIATE_SPIKE_WATCH",
    title: "Canva Affiliate — 36% Commission Spike",
    description: "Canva's affiliate program just spiked to 36% recurring commission (up from 20%). High conversion rate — 1 in 12 clicks converts.",
    url: "https://canva.com/affiliates", tags: ["affiliate","recurring","content","global"], category: "INSTANT_WIN", geoScope: "GLOBAL",
    scoreFriction:2, scorePayout:8, scoreTimeCost:1, scoreCompetition:6, scoreRisk:2, scoreDemand:9, scoreOverall:8.7,
    estimatedValue:"$50–200/mo", estimatedTime:"15 min setup",
    steps:["Apply at canva.com/affiliates (instant approval)","Get your unique referral link","Share in YouTube descriptions, social posts, or blog","Earn 36% recurring on every Pro signup"],
  },
  {
    id: "op-006", sourceEngine: "SKILL_SURGE",
    title: "Figma Plugin Dev — Low Competition, $400–800/mo Passive",
    description: "Figma plugin marketplace searches are up 180% in 6 weeks. Average plugin earns $400–800/mo. Competition is still low.",
    url: "https://figma.com/plugin-docs", tags: ["tech","passive","creative","freelance"], category: "SHORT_TERM", geoScope: "GLOBAL",
    scoreFriction:5, scorePayout:8, scoreTimeCost:5, scoreCompetition:3, scoreRisk:2, scoreDemand:9, scoreOverall:8.3,
    estimatedValue:"$400–800/mo", estimatedTime:"2–3 weeks",
    steps:["Study Figma plugin docs (free, 2 hrs)","Pick a pain point from Figma Community forums","Build a simple plugin (1–2 weeks)","List on Figma Community with a freemium model","Add paid tier at $5–15/mo"],
  },
  {
    id: "op-007", sourceEngine: "HUSTLE_VALIDATOR",
    title: "Prompt Engineering Gigs — $35–75/hr on Upwork",
    description: "Prompt engineering is one of the fastest-growing Upwork categories. No formal background required.",
    url: "https://upwork.com", tags: ["freelance","ai","noskills","remote"], category: "SHORT_TERM", geoScope: "GLOBAL",
    scoreFriction:4, scorePayout:7, scoreTimeCost:4, scoreCompetition:5, scoreRisk:2, scoreDemand:9, scoreOverall:7.9,
    estimatedValue:"$35–75/hr", estimatedTime:"1–2 weeks to first job",
    steps:["Create Upwork profile (free)","Write a niche bio about AI automation","Apply to 5–10 prompt engineering jobs","Deliver first project, collect review"],
  },
  {
    id: "op-008", sourceEngine: "GRANT_RADAR",
    title: "NEA Arts in Media Grant — Up to $10,000",
    description: "National Endowment for the Arts is accepting apps for the Arts in Media grant. Digital creators and app builders qualify. Deadline: 6 weeks.",
    url: "https://arts.gov", tags: ["grant","creative","tech","US"], category: "SHORT_TERM", geoScope: "US",
    scoreFriction:6, scorePayout:10, scoreTimeCost:5, scoreCompetition:4, scoreRisk:2, scoreDemand:8, scoreOverall:8.6,
    estimatedValue:"$10,000", estimatedTime:"3–5 hrs application",
    steps:["Check eligibility at arts.gov/grants","Register on grants.gov (30 min)","Write 500-word project narrative","Submit budget and work samples","Deadline: 6 weeks from now"],
  },
  {
    id: "op-009", sourceEngine: "AFFILIATE_SPIKE_WATCH",
    title: "ClickBank — New AI Tool Offer, 75% Commission",
    description: "A new AI productivity tool launched on ClickBank with 75% commission and $97 price point. Early affiliates have no competition.",
    url: "https://clickbank.com", tags: ["affiliate","ai","highticket","global"], category: "SHORT_TERM", geoScope: "GLOBAL",
    scoreFriction:3, scorePayout:9, scoreTimeCost:3, scoreCompetition:2, scoreRisk:4, scoreDemand:8, scoreOverall:8.8,
    estimatedValue:"$72.75/sale", estimatedTime:"1 week to first sale",
    steps:["Sign up at clickbank.com (free)","Find the offer in Marketplace","Request affiliate approval","Promote via email list, YouTube, or paid ads"],
  },
  {
    id: "op-010", sourceEngine: "MICRO_TASK_MINER",
    title: "Remotasks AI Data Labeling — $12–18/hr",
    description: "Remotasks is paying $12–18/hr for AI training data annotation. Work your own hours, paid weekly.",
    url: "https://remotasks.com", tags: ["microtask","ai","remote","noskills"], category: "SHORT_TERM", geoScope: "GLOBAL",
    scoreFriction:3, scorePayout:6, scoreTimeCost:2, scoreCompetition:5, scoreRisk:1, scoreDemand:9, scoreOverall:7.8,
    estimatedValue:"$12–18/hr", estimatedTime:"Days to first payout",
    steps:["Apply at remotasks.com","Complete onboarding quiz","Work available 24/7","Paid weekly via PayPal or bank transfer"],
  },
  {
    id: "op-011", sourceEngine: "LOCAL_ARBITRAGE_LENS",
    title: "PS5 Bundle — $280 Listed / $420 eBay Median",
    description: "PS5 Disc bundle listed locally at $280. Current eBay median: $420. Validated flip — est. profit: $90–110.",
    url: "https://facebook.com/marketplace", tags: ["arbitrage","local","validated","flip"], category: "SHORT_TERM", geoScope: "US",
    scoreFriction:2, scorePayout:7, scoreTimeCost:4, scoreCompetition:3, scoreRisk:3, scoreDemand:8, scoreOverall:8.0,
    estimatedValue:"$90–110 profit", estimatedTime:"3–7 days to sell",
    steps:["Contact seller — move fast","Inspect item on pickup","List on eBay with 10 photos","Ship within 2 days of sale"],
  },
  {
    id: "op-012", sourceEngine: "PAYOUT_PULSE",
    title: "Rakuten — $40 Bonus on First $40 Purchase",
    description: "Rakuten is running a 100% bonus offer — spend $40 through their portal, get $40 back. Works on 3,500+ stores.",
    url: "https://rakuten.com", tags: ["cashback","bonus","lowfriction","US"], category: "INSTANT_WIN", geoScope: "US",
    scoreFriction:1, scorePayout:7, scoreTimeCost:1, scoreCompetition:3, scoreRisk:1, scoreDemand:9, scoreOverall:8.9,
    estimatedValue:"$40", estimatedTime:"5 min",
    steps:["Sign up at rakuten.com","Install browser extension","Make any $40 purchase through the portal","$40 bonus paid via PayPal in 90 days"],
  },
  {
    id: "op-013", sourceEngine: "SKILL_SURGE",
    title: "No-Code SaaS with Bubble.io — $1k–5k/mo Potential",
    description: "Bubble.io no-code apps sell for $1k–5k/mo recurring. You can build a functional SaaS in 4–6 weeks with no coding background.",
    url: "https://bubble.io", tags: ["nocode","saas","passive","freelance"], category: "LONG_TERM", geoScope: "GLOBAL",
    scoreFriction:6, scorePayout:9, scoreTimeCost:7, scoreCompetition:4, scoreRisk:3, scoreDemand:9, scoreOverall:8.1,
    estimatedValue:"$1k–5k/mo", estimatedTime:"4–6 weeks",
    steps:["Complete Bubble Academy (free, 8 hrs)","Pick one specific pain point","Build MVP in 2–3 weeks","Launch on ProductHunt","Charge $29–99/mo per user"],
  },
  {
    id: "op-014", sourceEngine: "GRANT_RADAR",
    title: "SBIR Phase I Grant — Up to $275,000",
    description: "SBIR grants fund early-stage tech projects. Phase I awards up to $275k. Applications open quarterly.",
    url: "https://sbir.gov", tags: ["grant","tech","US","highvalue"], category: "LONG_TERM", geoScope: "US",
    scoreFriction:8, scorePayout:10, scoreTimeCost:8, scoreCompetition:5, scoreRisk:2, scoreDemand:7, scoreOverall:7.8,
    estimatedValue:"$275,000", estimatedTime:"3–6 months",
    steps:["Register your business at SAM.gov","Find a matching topic at sbir.gov","Write Phase I proposal (15 pages)","Submit and await review"],
  },
  {
    id: "op-015", sourceEngine: "HUSTLE_VALIDATOR",
    title: "Digital Product on Gumroad — Validated Category",
    description: "Notion templates, AI prompt packs, and spreadsheets are top Gumroad categories. Average creator earns $300–2,000/mo after 90 days.",
    url: "https://gumroad.com", tags: ["digital","passive","noskills","global"], category: "LONG_TERM", geoScope: "GLOBAL",
    scoreFriction:4, scorePayout:7, scoreTimeCost:6, scoreCompetition:6, scoreRisk:2, scoreDemand:8, scoreOverall:7.6,
    estimatedValue:"$300–2,000/mo", estimatedTime:"2–4 weeks to build",
    steps:["Pick category: Notion template, prompt pack, or spreadsheet","Build your product","Create Gumroad listing","Promote on Twitter/X, Reddit, Pinterest"],
  },
  {
    id: "op-c01", sourceEngine: "SKILL_SURGE",
    title: "Fund Your Figma Plugin Journey with NEA Grant",
    description: "Figma plugin development is trending (180% search increase) AND there's an active NEA Arts in Media grant. Apply first, use the $10k as runway while you build.",
    url: "https://arts.gov", tags: ["tech","creative","grant","freelance","compound"], category: "SHORT_TERM", geoScope: "US",
    scoreFriction:6, scorePayout:10, scoreTimeCost:5, scoreCompetition:3, scoreRisk:2, scoreDemand:9, scoreOverall:9.1,
    estimatedValue:"$10,000 + $400–800/mo", estimatedTime:"3–5 hrs grant + 2–3 weeks build",
    isCompound:true, compoundEngines:["SKILL_SURGE","GRANT_RADAR"], synergyBonus:1.2,
    steps:["Apply for NEA Arts in Media grant (deadline 6 weeks)","Study Figma plugin docs while waiting","Build your first plugin using grant as runway","Launch on Figma Community with freemium model"],
  },
  {
    id: "op-c02", sourceEngine: "AFFILIATE_SPIKE_WATCH",
    title: "Stack ClickBank Spike + Chase Cashback Bonus",
    description: "ClickBank has a 75% commission AI tool offer live NOW. Chase Sapphire has a $200 cashback bonus. Same week, two income streams activated in parallel.",
    url: "https://clickbank.com", tags: ["affiliate","cashback","compound","US"], category: "INSTANT_WIN", geoScope: "US",
    scoreFriction:3, scorePayout:9, scoreTimeCost:2, scoreCompetition:3, scoreRisk:3, scoreDemand:9, scoreOverall:9.3,
    estimatedValue:"$200 + $72/sale", estimatedTime:"25 min setup",
    isCompound:true, compoundEngines:["AFFILIATE_SPIKE_WATCH","PAYOUT_PULSE"], synergyBonus:1.25,
    steps:["Apply for Chase Sapphire (10 min)","Sign up for ClickBank affiliate (5 min)","Get approved for the AI tool offer","Share affiliate link in existing content"],
  },
  {
    id: "op-c03", sourceEngine: "FREEBIE_FORGE",
    title: "Launch AI Dev Career Using Free Credits + Trending Skill",
    description: "Together.ai is giving $25 free API credits AND prompt engineering is the fastest-growing Upwork category. Use credits to build a portfolio, then charge $35–75/hr.",
    url: "https://together.ai", tags: ["ai","free","freelance","compound","global"], category: "SHORT_TERM", geoScope: "GLOBAL",
    scoreFriction:3, scorePayout:8, scoreTimeCost:4, scoreCompetition:4, scoreRisk:1, scoreDemand:9, scoreOverall:8.9,
    estimatedValue:"$35–75/hr", estimatedTime:"1–2 weeks to first client",
    isCompound:true, compoundEngines:["FREEBIE_FORGE","SKILL_SURGE"], synergyBonus:1.1,
    steps:["Claim Together.ai free credits (3 min)","Build a small AI automation demo","Create Upwork profile with demo as portfolio","Apply to 5 prompt engineering jobs","Close first client at $35–75/hr"],
  },
];